import * as echarts from "echarts/core";
import { CanvasRenderer } from "echarts/renderers";
import {
  BarChart,
  LineChart,
  PieChart,
  MapChart,
  PictorialBarChart,
  RadarChart,
  GaugeChart,
  GraphChart,
  HeatmapChart,
  TreeChart,
  ScatterChart,
  EffectScatterChart,
  TreemapChart,
  SunburstChart,
  BoxplotChart,
  CandlestickChart,
  SankeyChart,
  FunnelChart,
  ThemeRiverChart,
  CustomChart
} from "echarts/charts";
import {
  TitleComponent,
  TooltipComponent,
  GridComponent,
  PolarComponent,
  AriaComponent,
  ParallelComponent,
  LegendComponent,
  RadarComponent,
  ToolboxComponent,
  DataZoomComponent,
  VisualMapComponent,
  TimelineComponent,
  CalendarComponent,
  GraphicComponent
} from "echarts/components";
echarts.use([
  BarChart,
  LineChart,
  PieChart,
  MapChart,
  PictorialBarChart,
  RadarChart,
  GaugeChart,
  GraphChart,
  HeatmapChart,
  TreeChart,
  ScatterChart,
  EffectScatterChart,
  TreemapChart,
  SunburstChart,
  BoxplotChart,
  CandlestickChart,
  SankeyChart,
  FunnelChart,
  ThemeRiverChart,
  CustomChart,
  LegendComponent,
  TitleComponent,
  TooltipComponent,
  GridComponent,
  PolarComponent,
  AriaComponent,
  ParallelComponent,
  RadarComponent,
  ToolboxComponent,
  DataZoomComponent,
  VisualMapComponent,
  TimelineComponent,
  CalendarComponent,
  GraphicComponent,
  CanvasRenderer
]);

export default echarts;